export const DASHBOARD_GET_REQUEST=" DASHBOARD_GET_REQUEST"
export const DASHBOARD_GET_SUCCESS=" DASHBOARD_GET_SUCCESS"
export const DASHBOARD_GET_FAILURE=" DASHBOARD_GET_FAILURE"

export const ADMINS_GET_REQUEST=" ADMINS_GET_REQUEST"
export const ADMINS_GET_SUCCESS=" ADMINS_GET_SUCCESS"
export const ADMINS_GET_FAILURE=" ADMINS_GET_FAILURE"

export const UPDATE_REQUEST=" UPDATE_REQUEST"
export const UPDATE_SUCCESS=" UPDATE_SUCCESS"
export const UPDATE_FAILURE=" UPDATE_FAILURE"