export const CART_POST_REQUEST="CART_POST_REQUEST"
export const CART_POST_SUCCESS="CART_POST_SUCCESS"
export const CART_POST_FAILURE="CART_POST_FAILURE"

export const CART_GET_REQUEST="CART_GET_REQUEST"
export const CART_GET_SUCCESS="CART_GET_SUCCESS"
export const CART_GET_FAILURE="CART_GET_FAILURE"

export const CART_PATCH_REQUEST="CART_PATCH_REQUEST"
export const CART_PATCH_SUCCESS="CART_PATCH_SUCCESS"
export const CART_PATCH_FAILURE="CART_PATCH_FAILURE"

export const CART_DELETE_REQUEST="CART_DELETE_REQUEST"
export const CART_DELETE_SUCCESS="CART_DELETE_SUCCESS"
export const CART_DELETE_FAILURE="CART_DELETE_FAILURE"

