export const CART_POST_REQUEST="CART_POST_REQUEST"
export const CART_POST_SUCCESS="CART_POST_SUCCESS"
export const CART_POST_FAILURE="CART_POST_FAILURE"

export const CART_GET_REQUEST="CART_GET_REQUEST"
export const CART_GET_SUCCESS="CART_GET_SUCCESS"
export const CART_GET_FAILURE="CART_GET_FAILURE"

