export const ORDER_POST_REQUEST="ORDER_POST_REQUEST"
export const ORDER_POST_SUCCESS="ORDER_POST_SUCCESS"
export const ORDER_POST_FAILURE="ORDER_POST_FAILURE"

export const ORDER_GET_REQUEST="ORDER_GET_REQUEST"
export const ORDER_GET_SUCCESS="ORDER_GET_SUCCESS"
export const ORDER_GET_FAILURE="ORDER_GET_FAILURE"